from abc import ABC, abstractmethod
from typing import List, Optional, Any
from langchain_core.runnables import RunnableConfig

class IAgent(ABC):
    """
    The orchestrator only depend on this interface.
    It does not know or care whether the underlying implementation uses 
    Hugging Face, OpenAI, Anthropic, or a simple mock for testing.
    """

    @property
    @abstractmethod
    def name(self) -> str:
        """
        Every agent must expose a name.
        This is crucial for logging, debugging, and routing within the graph.
        
        Returns:
            str: The defined name of the agent.
        """
        pass

    @abstractmethod
    def run(
        self, 
        user_input: str, 
        context: str = "", 
        chat_history: Optional[List[Any]] = None,
        config: Optional[RunnableConfig] = None
    ) -> str:
        """
        Executes the agent's core logic.
        
        All concrete agent classes MUST implement this method.
        
        Args:
            user_input (str): The main query or instruction from the user/node.
            context (str, optional): Additional data (e.g., ChromaDB chunks) 
                                     to ground the agent's response. Defaults to "".
            chat_history (Optional[List[Any]], optional): Previous conversation 
                                                          memory. Defaults to None.
                                                          
        Returns:
            str: The final text response generated by the agent.
        """
        pass

    @abstractmethod
    def invoke_with_tools(
        self,
        messages: List[Any],
        config: Optional[RunnableConfig] = None,
    ) -> Any:
        """
        Invokes the underlying LLM with bound tools for LangGraph tool-calling flows.
        """
        pass

    @property
    @abstractmethod
    def llm(self) -> Any:
        """The underlying language model instance.

        Exposing this via the interface allows graph nodes to use the LLM
        directly (e.g. for dynamic tool construction) without bypassing the
        abstraction or accessing private attributes on concrete classes.
        """
        pass

    @property
    @abstractmethod
    def tools(self) -> List[Any]:
        """The tools available to this agent."""
        pass