name: Deploy Frontend to HF
on:
  push:
    branches: ["feature/release"]
    paths:
      - 'src/frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Instalar Hugging Face CLI
        run: pip install -U "huggingface_hub[cli]"

      - name: Subir al Space (FRONTEND)
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          hf upload agaisina/agents-ui src/frontend/ . --repo-type space --token $HF_TOKEN